stages:
  data_ingestion:
    cmd: python src/detection/pipeline/stage_01_data_ingestion.py
    deps:
      - src/detection/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion


  prepare_base_model:
    cmd: python src/detection/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/detection/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - THRESHOLD
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src/detection/pipeline/stage_03_training.py
    deps:
      - src/detection/pipeline/stage_03_training.py
      - config/config.yaml
      - artifacts/data_ingestion
      - artifacts/prepare_base_model
    params:
      - THRESHOLD
    outs:
      - artifacts/training/model.joblib
