artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  root_folder: C:\\Users\\admin\\Desktop\\JI\\Project\\Capstone_CV\\h202_glucose
  local_data_file_gluscose: artifacts/data_ingestion/glucose
  local_data_file_h202: artifacts/data_ingestion/h202



prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.joblib
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.joblib




training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.joblib